// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://baceeegbbvekqfcpvhxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhY2VlZWdiYnZla3FmY3B2aHh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NjUzMTIsImV4cCI6MjA2NzM0MTMxMn0.4Kd6RrB9vY9Rn1RATYy3eIGPU-nzQYKs0bYA9P_oouI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);